### ISSUE TITLE
Error: " Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead."

### ISSUE THREAD

**Issue by JackokieZhao** [parnika31/MACAAC#1]
When I run your source 'main_treasure_collection.py', there exists the following problem:

Episodes 1-13 of 100000
/home/jackokie/ProgramFiles/anaconda/envs/torch0.4/lib/python3.7/site-packages/numpy/core/_asarray.py:171: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order, subok=True)
/home/jackokie/ProgramFiles/anaconda/envs/torch0.4/lib/python3.7/site-packages/numpy/core/_asarray.py:102: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  return array(a, dtype, copy=False, order=order)
/home/jackokie/ProgramFiles/anaconda/envs/torch0.4/lib/python3.7/site-packages/numpy/core/_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)
Traceback (most recent call last):
  File "./main_treasure_collection.py", line 233, in <module>
    run(config)
  File "./main_treasure_collection.py", line 158, in run
    penalty1_q, penalty2_q = model.update_penalty_critic(sample, logger=logger)
  File "/home/jackokie/MACAAC-main/algorithms/attention_sac_cons.py", line 166, in update_penalty_critic
    penalty_q = torch.from_numpy(asarray([ret[0].mean() for ret in critic_rets], dtype=float)).detach()
  File "/home/jackokie/ProgramFiles/anaconda/envs/torch0.4/lib/python3.7/site-packages/numpy/core/_asarray.py", line 102, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/jackokie/ProgramFiles/anaconda/envs/torch0.4/lib/python3.7/site-packages/torch/tensor.py", line 460, in __array__
    return self.numpy().astype(dtype, copy=False)
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

**Comment by parnika31** [comment]
Hi,

If you have not used the similar dependencies mentioned in the readme file, you may try that first. This problem seems to arise due to how numpy.asarray is coded in the version you are using. 

Otherwise you first disassociate gradient from the variable 'ret' in line 166 in attention_sac_cons.py and check if your issue is resolved.

**Comment by 2020jhj** [comment]
Hi, I used the similar dependencies mentioned in the readme file, but when I run your source 'main.py', there also exists the same problem:
Traceback (most recent call last):
  File "/home/jhj/python/MACAAC/main.py", line 216, in <module>
    run(config)
  File "/home/jhj/python/MACAAC/main.py", line 147, in run
    model.update_critic(sample, logger=logger)
  File "/home/jhj/python/MACAAC/algorithms/atten_sac_cons_2.py", line 104, in update_critic
    next_qs = self.target_critic(trgt_critic_in)
  File "/home/jhj/miniconda3/envs/pytorch1.1.0/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jhj/python/MACAAC/critics.py", line 173, in forward
    mean_att_wgts_per_agent = np.mean(np.asarray(mean_att_wgts_per_agent),0)
  File "/home/jhj/miniconda3/envs/pytorch1.1.0/lib/python3.7/site-packages/torch/tensor.py", line 458, in __array__
    return self.numpy()
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.
